---
- hosts: dev
  become: yes
  become_user: devuser
  tasks:
    - name: install python pip
      shell: "sudo apt install python-pip"
    - name: Install docker
      shell: "sudo apt install docker"
    - name: start docker
      shell: "sudo service docker start"
    - name: install docker-py python module
      shell: "sudo pip install docker-py"
    - name: start the container
      docker_container:
        name: docker-spring-boot
        image: "mmarinka/docker-spring-boot:latest"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
          - 0.0.0.0:3306:3306
