---
- hosts: dev
  become: yes
  become_user: devuser
  tasks:
    - name: install python pip
      shell: "sudo apt install python-pip"
    - name: Install docker
      shell: "sudo apt install docker"
    - name: start docker
      shell: "sudo service docker start"
    - name: install docker-py python module
      shell: "sudo pip install docker-py"
    - name: start the container
      shell: "docker container run -p 8080:8080 mmarinka/docker-spring-boot:latest"
      
