---
- hosts: dev
  become: true
  become_user: devuser
  tasks:
    - name: install python pip
      apt:
        update_cache: yes 
        name: python-pip
    - name: Install docker
      apt:
        name: docker
        state: present
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: start the container
      docker_container:
        name: docker-spring-boot
        image: mmarinka/docker-spring-boot:latest
        state: started
        published_ports:
         - 0.0.0.0:8080:8080
      
